### ISSUE TITLE
Error: In main chunk

### ISSUE THREAD

**Issue by Aurlia** [shirsig/CDFrames#1]
After just updating to the latest version I got the following errors.
Also cleared my WTF/addon folder from previous files.

AddOn: CDFrames
File: core.lua
Line: 15
Count: 1
---------------
AddOn: CDFrames
File: frame.lua
Line: 1
Count: 1
---------------
AddOn: CDFrames
File: player.lua
Line: 1
Count: 1
---------------
AddOn: CDFrames
File: enemy.lua
Line: 1
Count: 1

**Comment by shirsig** [comment]
Hey, thanks for reporting. I commited that prematurely I guess because I decided to make some quite extensive changes afterwards and it doesn't make much sense to go back to fix it at this point. I'd keep using the previous version until I'm done with the update in a day or two.

**Comment by Aurlia** [comment]
I've also had some errors from the old version but that one was at least working. Do you want me to report those errors also in case there is something you need to adjust in the new version ?

**Comment by shirsig** [comment]
Best wait for the new version first. I'm refactoring so much that it's very unlikely the same bugs would be there (but you have new ones to look forward to :))

**Comment by Aurlia** [comment]
Sounds like a good idea, thanks for the fantastic work!
