### ISSUE TITLE
Bloodthirst issue

### ISSUE THREAD

**Issue by cheech** [shirsig/cdframes#12]
Hello! 

Thanks for you work!

However, the warrior Bloodthirst ability cooldown is not working.

Thanks in advance!

**Comment by shirsig** [comment]
for your own or others?

**Comment by cheech** [comment]
My own, specifically. Not seing it when targeting myself as well...

**Comment by shirsig** [comment]
well, tested it on retrowow and it works fine. Try clean install, deleting savedvariables, the usual stuff

**Comment by cheech** [comment]
Deleted the addon folder, deleted the variables, even deleted wdb, reinstalled, and it doesn't work on Elysium... Can you please help with that?

**Comment by shirsig** [comment]
There's nothing I can do. I can't reproduce it without a warrior, I see no problem in the code. Try more to isolate the issue. e.g., make sure your client is closed when deleting the savedvariables, make sure all other addons disabled

**Comment by cheech** [comment]
i can give you my account for testing... i tried everything mate....

**Comment by cheech** [comment]
its a brilliant addon of yours, i want to use it so damn much. but i cant, if it doesnt track bloodthirst....

**Comment by shirsig** [comment]
Don't want to get either of us banned :/
It tracks every other cooldown fine?

**Comment by cheech** [comment]
yes. the only problem is the Bloodthirst.

**Comment by shirsig** [comment]
do you use it through some sort of macro?

**Comment by shirsig** [comment]
have you tried to disable **/cdframes used**

**Comment by cheech** [comment]
Yes! That was the problem!

The macro is to swap to zerk stance before using BT... its a useful one tho...

**Comment by shirsig** [comment]
ah, yeah, well, you can have that if you disable **/cdframes used** but then you'll get icons for shared cooldowns (like multiple potions cds after using one)
I'll try if I can fix it with the used mode.

**Comment by cheech** [comment]
Thank you so much!
