### ISSUE TITLE
Ability tracking issue.

### ISSUE THREAD

**Issue by vasecha** [shirsig/cdframes#13]
For some reason cdframes doesnt track Power Infusion spell. Is there any way to "add" this spell to the tracking by myself? 
Thank you.

**Comment by dimukka** [comment]
I have the same problem with frost nova

**Comment by shirsig** [comment]
I assume you're talking about enemy cooldowns (big difference). Sometimes it's simply not possible to track them because there's not enough information in the combat log. You can enable all combat log messages and check for yourself.

**Comment by dimukka** [comment]
enemy frost nova I can understand but it is not tracking my own nova either. I changed the cooldown in the lua file from 25 to 21 because of my spec, and also the icon to same as hunter frost trap and it worked briefly, but now its stopped working again.

**Comment by shirsig** [comment]
You shouldn't change anything, your cooldowns are tracked differently from enemy cooldowns.

**Comment by dimukka** [comment]
yeah I tried changing it because it wasnt working, after the change it worked briefly but not anymore

**Comment by shirsig** [comment]
well, it works fine for me so you must be doing something wrong. some other addon or you didn't properly install

**Comment by dimukka** [comment]
aight I'll try disabling some and see if that's the cause, everyother cooldown works great. Ty for help man!
