### ISSUE TITLE
disable your own cooldowns showing up when self-targeting?

### ISSUE THREAD

**Issue by wayser** [shirsig/cdframes#14]
just something small and i'm not sure if it would be easy or not, a niche request that's more of a preference. is it possible to add a line somewhere that would stop my own cooldowns from showing up when self-targeting?

**Comment by shirsig** [comment]
Actually you should be able to do this without changing the code, like: /cdframes frame target not UnitIsPlayer'target' and UnitName'target'

**Comment by wayser** [comment]
thanks i'll try it out!
