### ISSUE TITLE
Spell not correctly

### ISSUE THREAD

**Issue by chenningfugg** [shirsig/cdframes#15]
Fantastic things! Recently,I find asmall issue that this addon couldn't display the cooldown times of Arcane Power.Hope u guys could fix it!

**Comment by shirsig** [comment]
Hm, I don't see an obvious reason why it wouldn't work. Are you using the newest version, english client, tried without other addons etc? And I assume you're talking about enemy cooldowns, not your own? Any other spells that don't work? Arcane power should be detected the same way as other gains (i.e., combat log message "**unit** gains **effect**.")

**Comment by chenningfugg** [comment]
ty,I'll try tonight.
