### ISSUE TITLE
CDs not displaying with mouseovers

### ISSUE THREAD

**Issue by PlannedTuna** [shirsig/cdframes#16]
I am using mouseover macros with luna unit frames (which is rather common since luna is the standard for healers), and have noticed that if I cast a spell with a cooldown via mouseover, cdframes will not display the cooldown unless I have the "cdframes used" setting turned off. Unfortunately however, turning the setting off will of course cause all of my potions/items that share cooldowns to show up when I use them which is not the most desirable work-around. Here is an example of one of the macros I'm referring to:

/lunamo Blessing of Protection(Rank 3) 

As you can see the macro is nothing fancy. I don't know if it would be possible to fix this easily, but if so I would really appreciate it. Another possible work-around would be adding the ability to put items in the ignore list, but I'm not sure how easy/doable that would be. I've tested with all other addons disabled besides Luna Unit Frames/CDFrames.

**Comment by shirsig** [comment]
Had nothing to do with luna per se, you would've gotten the same issue with /cast (because either the rank part or lowercase spell names, but it should be fixed now.

**Comment by PlannedTuna** [comment]
Thanks!
