### ISSUE TITLE
Sort cooldowns by age

### ISSUE THREAD

**Issue by L8rspacecowboy** [shirsig/cdframes#20]
I think it would be a good addition if you made it so the cooldown that was cast first stayed in it's original spot rather than moved over when a new one is casted. For instance, Blink was cast first, so it would look like this
[Blink]  then [Frost Nova] [Fire Ward] [Cold Snap]

When each expires the one closest takes its place.
[Frost Nova] [Fire Ward] [Cold Snap]

Then

[Fire Ward] [Cold Snap][Blink]

It will make it easier to keep track of new cooldowns, so longer ones like Evocation and coldsnap aren't moving around all over the place.

**Comment by shirsig** [comment]
I'd think they would move around about the same. Right now coldsnap/evocation only move when you get a new cooldown with a longer time remaining. With sorting by starting time they would move whenever a lower one that was already active expires.

**Comment by shirsig** [comment]
added a setting for it: /cdframes order start
(or /cdframes order remaining)
