### ISSUE TITLE
Reverse order of cooldowns shown possible?

### ISSUE THREAD

**Issue by dabadoo** [shirsig/cdframes#24]
Currently the cooldowns with the longest time left are displayed first.

Do any commands exist that inverts this behavior so short cooldowns are displayed first in line? Or is it possible to make a quick edit in the config files?

**Comment by shirsig** [comment]
here https://github.com/shirsig/cdframes/blob/master/frame.lua#L364
make it **ta < tb**

**Comment by dabadoo** [comment]
Works great. Thank you!
