### ISSUE TITLE
Judgement cooldown

### ISSUE THREAD

**Issue by Killval** [shirsig/cdframes#27]
Just curious I've used this addon and loved it on my various characters such as Warrior/Mage/Hunter with no issues. When I go on my Paladin, and my one offensive ability is on a 10 second or 8 second cooldown if talented. This ability will NOT show up on the addon for odd reason, idk if it is because of the short timing or what, or if there is some sort of work-around? Please help.

**Comment by Killval** [comment]
Nvm I figured it out, it was because the Judgement spell I was using was in a macro, can it still show the icon cooldown even if the spell is in a macro somehow?

**Comment by shirsig** [comment]
Same as this: https://github.com/shirsig/cdframes/issues/22
if you deactivate **/cdframes used**
