### ISSUE TITLE
Add focus support

### ISSUE THREAD

**Issue by Bifidus** [shirsig/cdframes#28]

**Comment by shirsig** [comment]
There's no focus in vanilla. If you mean a custom frame from some addon the readme describes how to add those.

**Comment by Bifidus** [comment]
Oh, nice, thank you :)

**Comment by Bifidus** [comment]
Maybe this error is related ?
![capture d ecran_2018-05-27_04-56-58](https://user-images.githubusercontent.com/336778/40582088-c4e5ab4e-616a-11e8-9ea2-3717721d1cd1.png)

**Comment by shirsig** [comment]
Seems like that focus addon I linked in my comments changed. Now it should be **/cdframes frame focus FocusCore:GetName()**
This has nothing to do with cdframes and if you're using a different focus addon/in general you have to ask the developer of that addon for the expression needed.
As for the error, try updating to the newest version/deleting the savedvariables, but don't think it had anything to do with this.

**Comment by Bifidus** [comment]
So, i tried different ways, with the help of the discord pfUI channel [https://discordapp.com/channels/329940978498666506/329940978498666506](url) (the focus addon i use), but no luck so far. The frame name is pfFocus (obtained with /run message(GetMouseFocus():GetName())). Whatever combination of /cdframes focus xxx i try, i always end up the same: a frame is created, but don't have any use.

**Comment by shirsig** [comment]
The "xxx" part must be an expression which evaluates to the name of the unit currently associated with the frame. It could for example be the name of the variable where pfui stores the name of the focused unit, or some pfui function call like (making this up) pfui:getCurrentFocusName()

**Comment by shirsig** [comment]
Try this: **/cdframes frame focus pfUI and pfUI.uf and pfUI.uf.focus and pfUI.uf.focus.unitname**

**Comment by Altoholic** [comment]
no change: the frame is created, but don't have any use.

**Comment by shirsig** [comment]
Did you use the updated version? This works for me: **/cdframes frame focus pfUI and pfUI.uf and pfUI.uf.focus and pfUI.uf.focus.unitname and gsub(pfUI.uf.focus.unitname, '^%l', strupper)**

**Comment by shirsig** [comment]
Great :) I'll add this one to the readme.

**Comment by Altoholic** [comment]
ty!
