### ISSUE TITLE
[request] make focus cooldowns disappear with /clearfocus

### ISSUE THREAD

**Issue by Altoholic** [shirsig/cdframes#29]
When i /clearfocus, the frame (from pfUI) disappear, but the cooldowns from cdframes stay. I suppose it would make more sense to get rid of them with the /clearfocus command.

**Comment by shirsig** [comment]
/cdframes frame focus pfUI and pfUI.uf and pfUI.uf.focus and pfUI.uf.focus:IsShown() and pfUI.uf.focus.unitname and gsub(pfUI.uf.focus.unitname, '^%l', strupper)

This should do it. Updated the readme too.
