### ISSUE TITLE
traps

### ISSUE THREAD

**Issue by Monteo** [shirsig/cdframes#31]
![wowscrnshot_071318_221942](https://user-images.githubusercontent.com/24656088/42699490-22abf864-86eb-11e8-8f6d-c2988051d3e1.jpg)
why shows the cd for all the traps, I understand that they have a common cd and one badge in particular

**Comment by Monteo** [comment]
cdframes = {
	["used"] = true,

**Comment by shirsig** [comment]
Without "used" it's expected, but with used enabled only one should show. will check it out.

**Comment by shirsig** [comment]
Bug was introduced with the arcane shot/multiple spells in macro change. Should be working again.

**Comment by Monteo** [comment]
thanks
