### ISSUE TITLE
[request] make any frame optional

### ISSUE THREAD

**Issue by Altoholic** [shirsig/cdframes#33]
I want to disable the player frame (but still keep the target and focus ones), but i don't think it's possible.

**Comment by shirsig** [comment]
**/cdframes player** should do it.

**Comment by Altoholic** [comment]
It's not.
/cdframes player don't seem to have any action. No error message. No message at all, actually.

**Comment by shirsig** [comment]
Pretty sure it used to work at least. There probably wasnt a message anyway. Ill try to check it this weekend.

**Comment by shirsig** [comment]
Sorry it's **/cdframes frame player**

**Comment by Altoholic** [comment]
Perfect. TY! :)
