### ISSUE TITLE
Issue with paladin abilities

### ISSUE THREAD

**Issue by fidbugs** [shirsig/cdframes#9]
Some abilities like Divine Protection, Divine Shield, Divine Favor, Blessing of Protection, are not tracked unless /cooldowns used is set to off. But then there is issue of when using a potion it shows cool down for every potion in your bag, which results in having like 5 extra slots filled, which is "polluting" my cool down frames.

Is there any way to fix it? I like addon very much and would like to continue using it, and fixing this would be most useful, not just for me but any paladin. Thank you!

**Comment by shirsig** [comment]
well, i leveled a paladin to 6 and divine protection works fine.
